"use client";

import React, { useState, useEffect, useCallback } from "react";
import { AlertTriangle, CheckCircle, ShieldCheck, Filter, Clock } from "lucide-react";
import { ClientShell } from "@/components/ClientShell";
import { api } from "@/lib/api";
import { Alert, AlertStatus } from "@/types";
import { useWebSocketTelemetry, WSEventMessage } from "@/lib/websocket";

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [filterStatus, setFilterStatus] = useState<string>("");
  const [isLoading, setIsLoading] = useState(true);

  const loadAlerts = useCallback(async () => {
    try {
      const data = await api.getAlerts(filterStatus || undefined);
      setAlerts(data);
    } catch (e) {
      console.error("Failed to load alerts:", e);
    } finally {
      setIsLoading(false);
    }
  }, [filterStatus]);

  useEffect(() => {
    loadAlerts();
  }, [loadAlerts]);

  useWebSocketTelemetry(
    useCallback((msg: WSEventMessage) => {
      if (msg.type === "alert.created") {
        setAlerts((prev) => [msg.data, ...prev]);
      } else if (msg.type === "alert.updated") {
        setAlerts((prev) =>
          prev.map((a) => (a.alert_id === msg.data.alert_id ? { ...a, status: msg.data.status } : a))
        );
      }
    }, [])
  );

  const handleAcknowledge = async (id: string) => {
    try {
      await api.acknowledgeAlert(id);
      setAlerts((prev) =>
        prev.map((a) => (a.alert_id === id ? { ...a, status: "ACKNOWLEDGED" as AlertStatus } : a))
      );
    } catch (e) {
      alert("Failed to acknowledge alert");
    }
  };

  const handleResolve = async (id: string) => {
    try {
      await api.resolveAlert(id);
      setAlerts((prev) =>
        prev.map((a) => (a.alert_id === id ? { ...a, status: "RESOLVED" as AlertStatus } : a))
      );
    } catch (e) {
      alert("Failed to resolve alert");
    }
  };

  return (
    <ClientShell>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-xl font-bold text-slate-900 tracking-tight">Real-Time Security Alerts</h1>
            <p className="text-xs text-slate-500">
              Correlated alerts generated by the composite risk engine and dual detection layers
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2 text-xs">
              <Filter className="h-3.5 w-3.5 text-slate-400" />
              <select
                value={filterStatus}
                onChange={(e) => setFilterStatus(e.target.value)}
                className="bg-white border border-slate-200 text-slate-700 text-xs rounded-md px-2.5 py-1.5 focus:outline-none focus:ring-1 focus:ring-indigo-500"
              >
                <option value="">All Statuses</option>
                <option value="NEW">New</option>
                <option value="ACKNOWLEDGED">Acknowledged</option>
                <option value="RESOLVED">Resolved</option>
              </select>
            </div>
          </div>
        </div>

        {/* Alerts Table */}
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 uppercase tracking-wider font-semibold">
              <tr>
                <th className="px-4 py-3">Alert ID</th>
                <th className="px-4 py-3">Attack Classification</th>
                <th className="px-4 py-3">Severity</th>
                <th className="px-4 py-3">Risk Score</th>
                <th className="px-4 py-3">Sensor Origin</th>
                <th className="px-4 py-3">Confidence</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Timestamp</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan={9} className="py-12 text-center text-slate-400">
                    No alerts yet
                  </td>
                </tr>
              ) : (
                alerts.map((a) => (
                  <tr key={a.alert_id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="px-4 py-3 font-mono font-bold text-slate-800">
                      {a.alert_id}
                      {a.is_test && (
                        <span className="ml-1.5 px-1 py-0.2 rounded text-[9px] font-bold bg-amber-100 text-amber-800">
                          TEST
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-3 font-semibold text-slate-900">{a.attack_type}</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                          a.severity === "CRITICAL"
                            ? "bg-rose-100 text-rose-800"
                            : a.severity === "HIGH"
                            ? "bg-amber-100 text-amber-800"
                            : "bg-blue-100 text-blue-800"
                        }`}
                      >
                        {a.severity}
                      </span>
                    </td>
                    <td className="px-4 py-3 font-bold text-slate-900">{a.risk_score}</td>
                    <td className="px-4 py-3 text-slate-600 font-mono text-[11px]">{a.client_id}</td>
                    <td className="px-4 py-3 text-slate-600">{(a.confidence * 100).toFixed(1)}%</td>
                    <td className="px-4 py-3">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-semibold ${
                          a.status === "NEW"
                            ? "bg-rose-50 text-rose-700 border border-rose-200"
                            : a.status === "ACKNOWLEDGED"
                            ? "bg-amber-50 text-amber-700 border border-amber-200"
                            : "bg-emerald-50 text-emerald-700 border border-emerald-200"
                        }`}
                      >
                        {a.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-400">
                      {new Date(a.timestamp).toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right space-x-2">
                      {a.status === "NEW" && (
                        <button
                          onClick={() => handleAcknowledge(a.alert_id)}
                          className="px-2 py-1 bg-amber-50 text-amber-700 border border-amber-200 rounded hover:bg-amber-100 transition-colors text-[11px] font-medium"
                        >
                          Acknowledge
                        </button>
                      )}
                      {a.status !== "RESOLVED" && (
                        <button
                          onClick={() => handleResolve(a.alert_id)}
                          className="px-2 py-1 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded hover:bg-emerald-100 transition-colors text-[11px] font-medium"
                        >
                          Resolve
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </ClientShell>
  );
}
