import pytest
from backend.app.services.privacy_service import privacy_engine

def test_pseudonym_generation():
    token1 = privacy_engine.generate_pseudonym("alice@example.com", prefix="USER")
    token2 = privacy_engine.generate_pseudonym("alice@example.com", prefix="USER")
    token3 = privacy_engine.generate_pseudonym("bob@example.com", prefix="USER")

    assert token1.startswith("USER-")
    assert token1 == token2, "Pseudonyms must be deterministic given identical inputs and salt"
    assert token1 != token3, "Different inputs must produce different pseudonym tokens"

def test_sensitive_field_redaction():
    raw_event = {
        "event_id": "EVT-TEST-01",
        "source": "192.168.1.50",
        "destination": "10.0.0.1",
        "metadata": {
            "user": "developer_john",
            "password": "CleartextPassword999!",
            "api_key": "Bearer secret_api_key_value_xyz",
            "department": "Engineering"
        }
    }

    sanitized, transforms = privacy_engine.process_telemetry_event(raw_event)

    assert sanitized["metadata"]["password"] == "[REDACTED]"
    assert sanitized["metadata"]["api_key"] == "[REDACTED]"
    assert sanitized["metadata"]["user"].startswith("USER-")
    assert sanitized["metadata"]["department"] == "Engineering"
    assert len(transforms) >= 3

def test_inline_email_redaction():
    text = "Alert generated by analyst: contact lead-sec@organization.org or call 555-123-4567"
    sanitized, transforms = privacy_engine.sanitize_string_pii(text)
    assert "lead-sec@organization.org" not in sanitized
    assert "USER-" in sanitized
    assert "555-123-4567" not in sanitized
    assert "[REDACTED-PHONE]" in sanitized

def test_cloud_and_token_redaction():
    text = "Found AWS AKIAIOSFODNN7EXAMPLE and token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozG69wUSWD8c69z at host 00:1A:2B:3C:4D:5E"
    sanitized, transforms = privacy_engine.sanitize_string_pii(text)
    assert "AKIAIOSFODNN7EXAMPLE" not in sanitized
    assert "[REDACTED-AWS-KEY]" in sanitized
    assert "eyJhbGci" not in sanitized
    assert "[REDACTED-JWT-TOKEN]" in sanitized
    assert "00:1A:2B:3C:4D:5E" not in sanitized
    assert "[REDACTED-MAC]" in sanitized
